# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

    exceptions:
        App\Exception\NotFoundException:
            log_level: notice
            status_code: 404
        App\Exception\BusinessRuleException:
            log_level: warning
            status_code: 422

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
